# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 浮生梦
subtitle: Cheney' blog
description: 夫天地者，万物之逆旅也；光阴者，百代之过客也。而浮生若梦，为欢几何？
keywords: 浮生梦 c++ cmake rust gcc g++ makefile 
author: 浮生梦
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://szrushi.github.io
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - lib/**/*
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
  exclude_languages:
    - mermaid

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/

# nofollow 标签是由谷歌领头创新的一个反垃圾链接的标签，并被百度、yahoo 等各大搜索引擎广泛支持.
# 引用 nofollow 标签的目的是：用于指示搜索引擎不要追踪（即抓取）网页上的带有 nofollow 属性的任何出站链接，以减少垃圾链接的分散网站权重。
# 这里推荐 hexo-autonofollow 插件来解决。
nofollow:
  enable: true
  exclude: # 例外的链接，可将友情链接放置此处
    - https://shiying.gushihose.com

# 安装搜索插件
# npm install hexo-generator-searchdb --save
# Local Search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
search:
  path: search.xml
  field: post
  content: true
  format: html
  limit: 1000

# https://github.com/dailyrandomphoto/hexo-unique-post-path
# This plug-n helps Hexo create new posts with unique auto-generated paths.
# npm install --save hexo-unique-post-path
# see https://github.com/dailyrandomphoto/hexo-unique-post-path
# unique_post_path:
#   auto: true
#   title_default: "auto post title"
#   type: nanoid-lowercase
#   size: 5



# A hexo plugin which is used to have all images support lazyload automatically.
# With the help of this functionality,
# it will improve lots of the loading proformance,
# base on hexo-lazyload-image .
# npm install hexo-lazyload-image-better --save
# see https://github.com/rqh656418510/hexo-lazyload-image-better
lazyload:
  enable: true
  imgContainer: true
  post:
     only: true
     excludeEncrypt: true
  loadingImg: # eg /images/loading.gif

# hexo-renderer-markdown-it
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix: 'language-'
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - 'markdown-it-footnote'
    - 'markdown-it-ins'
    - 'markdown-it-mark'
    - 'markdown-it-sub'
    - 'markdown-it-sup'
  #   # 自定义插件
    - 'markdown-it-checkbox'
    - 'markdown-it-emoji'
    - 'markdown-it-kbd'
    # - 'markdown-it-imsize'
    - 'markdown-it-named-headings'
    - plugin:
      name: markdown-it-imsize
      options:
        autofill: true
    - plugin:
      name: markdown-it-color-text
      options:
        classPrefix: 'md-colorify'
        inlineStyle: true
        customColor:
          primary: '#409EFF'
          success: '#67C23A'
          info: '#909399'
          warning: '#E6A23C'
          error: '#F56C6C'
    - plugin:
      name: '@traptitech/markdown-it-katex'
      options: # see https://katex.org/docs/options.html
        # katex: 0.15.3
        blockClass: "math-block"
        strict: false
        throwOnError: false
        errorColor: "#cc0000"
    - plugin:
      name: markdown-it-multimd-table
      enable: true
      options:
        multiline: true
        rowspan: true
        headerless: true
  anchors:
    # level: 2
    # collisionSuffix: 'v'
    permalink: false
  #   permalinkClass: 'header-anchor'
  #   permalinkSide: 'left'
  #   permalinkSymbol: ''
  #   case: 0
  #   separator: '-'

## Themes: https://hexo.io/themes/
theme: next
# theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git 
  repo:
    github: szrushi/szrushi.github.io
    branch: gh-pages